# Generated by Django 3.0.3 on 2021-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='path',
            field=models.FilePathField(default='/home/purnima/Downloads/webapp/testapp/Deep-learning-model-deploy-with-django/media', path='/home/purnima/Downloads/webapp/testapp/Deep-learning-model-deploy-with-django/media'),
        ),
    ]
